version: "3"
services:
  db:
    container_name: db
    image: mysql:5.6
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - 17001:3306
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
    restart: always
  vulnerable:
    container_name: vulnerable
    build: ./vulnerable
    volumes:
      - ./volumes/vulnerable/logs:/usr/src/vulnerable/logs
    ports:
      - 18001:5000
    depends_on:
      - db
    restart: always
