version: "3"
services:
  db:
    container_name: db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
    ports:
      - 17001:3306
    restart: always
  temporary:
    container_name: temporary
    build: ./vulnerable
    ports:
      - 18001:5000
    depends_on:
      - db
    restart: always
